apiVersion: v1
kind: Service
metadata:
  name: Valentine-App
  namespace: namespace-workflow-1710128054218
spec:
  type: LoadBalancer
  selector:
    app: Valentine-App
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080